### ISSUE TITLE
Error in setting up container

### ISSUE THREAD

**Issue by BC89** [Azure-Samples/container-apps-store-api-microservice#37]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Simply fork and clone the solution with the latest VSCode and remote container extension. VSCode recognizes a devcontainer exists and attempts to launch the container as expected. This fails.  

### Any log messages given by the failure

#0 7.919 /tmp/library-scripts/docker-in-docker-debian.sh: line 30: `    for CURR
'NT_USER in ${POSSIBLE_USERS[@]}; do
------
ERROR: failed to solve: executor failed running [/bin/sh -c apt-get update     &
& apt-get install python3-pip -y     && /bin/bash /tmp/library-scripts/docker-in
-docker-debian.sh "${ENABLE_NONROOT_DOCKER}" "${USERNAME}" "${USE_MOBY}" "${DOCK
ER_VERSION}"]: exit code: 2
[14641 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\BRENDA~1.CAR\AppData\Local\Temp\devcontainercli\container-features\0.25.2-1671545349879\Dockerfile-with-features -t vsc-container-apps-store-api-microservice-67bbad297964f83c0094e4ae069498d5 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label c:\temp\container-apps-store-api-microservice\.devcontainer
[14641 ms]     at Doe (c:\Users\brendan.carroll\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:1894:1669)
[14641 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[14641 ms]     at async EF (c:\Users\brendan.carroll\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:1893:1978)
[14642 ms]     at async uT (c:\Users\brendan.carroll\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:1893:901)
[14642 ms]     at async Poe (c:\Users\brendan.carroll\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:1899:2128)
[14642 ms]     at async Zf (c:\Users\brendan.carroll\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:1899:3278)
[14642 ms]     at async aue (c:\Users\brendan.carroll\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:2020:15276)
[14642 ms]     at async oue (c:\Users\brendan.carroll\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:2020:15030)
[14653 ms] Exit code 1
[14657 ms] Command failed: C:\Users\brendan.carroll\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\brendan.carroll\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\brendan.carroll\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\temp\container-apps-store-api-microservice --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\temp\container-apps-store-api-microservice --log-level debug --log-format json --config c:\temp\container-apps-store-api-microservice\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[14657 ms] Exit code 1
>

### Expected/desired behavior
Open as expected
>

### OS and Version?
> Windows 10.

### Versions
Version: 1.74.1 (user setup)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:30:51.966Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by BC89** [comment]
This issue seems like a UNIX EOF setting in the scripts which I would assume only impacts Windows users.
